<%@ page contentType="text/html; charset=euc-kr" pageEncoding="EUC-KR" %>
<%@ include file="dbConn.jsp" %>
<%@ page import="java.util.*,java.text.*"%>
<%@page import="org.json.simple.*"%>
<%
/* 
	중요!!!
	Json 형태로 출력하는 jsp페이지는 어떠한 html 요소도 사용하지 않아야 한다.
	<!DOCTYPE, <html 등등
*/
try{
	
String division = request.getParameter("division");
	
	String adm1 = request.getParameter("adm1"); //시도
	String adm2 = request.getParameter("adm2"); //군구
	String adm3 = request.getParameter("adm3"); //동
	
	//out.print(adm3);
	
	
		
		sql  = " SELECT 																																														";
		sql  += " '' AS YYYY, '' AS ADM_CD, '' AS DO_NM, '' AS CTY_NM, '' AS DONG_NM , '' AS RI_NM,                 ";
		sql  += " SUM ( gnr_flow_sum ) AS gnr_flow_sum ,                                                 ";
		sql  += " SUM ( gnr_flow_pop                    ) AS  gnr_flow_pop                    ,                     ";
		sql  += " SUM ( gnr_flow_ani          ) AS  gnr_flow_ani          ,                                         ";
		sql  += " SUM ( gnr_flow_ind          ) AS  gnr_flow_ind          ,                                         ";
		sql  += " SUM ( gnr_flow_land         ) AS  gnr_flow_land         ,                                         ";
		sql  += " SUM ( gnr_flow_fish         ) AS  gnr_flow_fish         ,                                         ";
		sql  += " SUM ( gnr_flow_landfill     ) AS  gnr_flow_landfill     ,                                         ";
		sql  += " SUM ( gnr_BOD_pop           ) AS  gnr_BOD_pop           ,                                         ";
		sql  += " SUM ( gnr_BOD_ani           ) AS  gnr_BOD_ani           ,                                         ";
		sql  += " SUM ( gnr_BOD_ind           ) AS  gnr_BOD_ind           ,                                         ";
		sql  += " SUM ( gnr_BOD_land          ) AS  gnr_BOD_land          ,                                         ";
		sql  += " SUM ( gnr_BOD_fish          ) AS  gnr_BOD_fish          ,                                         ";
		sql  += " SUM ( gnr_BOD_landfill      ) AS  gnr_BOD_landfill      ,                                         ";
		sql  += " SUM ( gnr_TN_pop            ) AS  gnr_TN_pop            ,                                         ";
		sql  += " SUM ( gnr_TN_ani            ) AS  gnr_TN_ani            ,                                         ";
		sql  += " SUM ( gnr_TN_ind            ) AS  gnr_TN_ind            ,                                         ";
		sql  += " SUM ( gnr_TN_land           ) AS  gnr_TN_land           ,                                         ";
		sql  += " SUM ( gnr_TN_fish           ) AS  gnr_TN_fish           ,                                         ";
		sql  += " SUM ( gnr_TN_landfill       ) AS  gnr_TN_landfill       ,                                         ";
		sql  += " SUM ( gnr_TP_pop            ) AS  gnr_TP_pop            ,                                         ";
		sql  += " SUM ( gnr_TP_ani            ) AS  gnr_TP_ani            ,                                         ";
		sql  += " SUM ( gnr_TP_ind            ) AS  gnr_TP_ind            ,                                         ";
		sql  += " SUM ( gnr_TP_land           ) AS  gnr_TP_land           ,                                         ";
		sql  += " SUM ( gnr_TP_fish           ) AS  gnr_TP_fish           ,                                         ";
		sql  += " SUM ( gnr_TP_landfill       ) AS  gnr_TP_landfill       ,                                         ";
		sql  += " SUM ( drt_flow_sum          ) AS  drt_flow_sum          ,                                         ";
		sql  += " SUM ( drt_flow_pop          ) AS  drt_flow_pop          ,                                         ";
		sql  += " SUM ( drt_flow_ani          ) AS  drt_flow_ani          ,                                         ";
		sql  += " SUM ( drt_flow_ind          ) AS  drt_flow_ind          ,                                         ";
		sql  += " SUM ( drt_flow_land         ) AS  drt_flow_land         ,                                         ";
		sql  += " SUM ( drt_flow_fish         ) AS  drt_flow_fish         ,                                         ";
		sql  += " SUM ( drt_flow_landfill     ) AS  drt_flow_landfill     ,                                         ";
		sql  += " SUM ( drt_BOD_sum           ) AS  drt_BOD_sum           ,                                         ";
		sql  += " SUM ( drt_BOD_pop           ) AS  drt_BOD_pop           ,                                         ";
		sql  += " SUM ( drt_BOD_ani           ) AS  drt_BOD_ani           ,                                         ";
		sql  += " SUM ( drt_BOD_ind           ) AS  drt_BOD_ind           ,                                         ";
		sql  += " SUM ( drt_BOD_land          ) AS  drt_BOD_land          ,                                         ";
		sql  += " SUM ( drt_BOD_fish          ) AS  drt_BOD_fish          ,                                         ";
		sql  += " SUM ( drt_BOD_landfill      ) AS  drt_BOD_landfill      ,                                         ";
		sql  += " SUM ( drt_TN_sum            ) AS  drt_TN_sum            ,                                         ";
		sql  += " SUM ( drt_TN_pop            ) AS  drt_TN_pop            ,                                         ";
		sql  += " SUM ( drt_TN_ani            ) AS  drt_TN_ani            ,                                         ";
		sql  += " SUM ( drt_TN_ind            ) AS  drt_TN_ind            ,                                         ";
		sql  += " SUM ( drt_TN_land           ) AS  drt_TN_land           ,                                         ";
		sql  += " SUM ( drt_TN_fish           ) AS  drt_TN_fish           ,                                         ";
		sql  += " SUM ( drt_TN_landfill       ) AS  drt_TN_landfill       ,                                         ";
		sql  += " SUM ( drt_TP_sum            ) AS  drt_TP_sum            ,                                         ";
		sql  += " SUM ( drt_TP_pop            ) AS  drt_TP_pop            ,                                         ";
		sql  += " SUM ( drt_TP_ani            ) AS  drt_TP_ani            ,                                         ";
		sql  += " SUM ( drt_TP_ind            ) AS  drt_TP_ind            ,                                         ";
		sql  += " SUM ( drt_TP_land           ) AS  drt_TP_land           ,                                         ";
		sql  += " SUM ( drt_TP_fish           ) AS  drt_TP_fish           ,                                         ";
		sql  += " SUM ( drt_TP_landfill       ) AS  drt_TP_landfill       ,                                         ";
		sql  += " SUM ( ind_cut_flow_sum      ) AS  ind_cut_flow_sum      ,                                         ";
		sql  += " SUM ( ind_cut_flow_pop      ) AS  ind_cut_flow_pop      ,                                         ";
		sql  += " SUM ( ind_cut_flow_ani      ) AS  ind_cut_flow_ani      ,                                         ";
		sql  += " SUM ( ind_cut_flow_ind      ) AS  ind_cut_flow_ind      ,                                         ";
		sql  += " SUM ( ind_cut_flow_land     ) AS  ind_cut_flow_land     ,                                         ";
		sql  += " SUM ( ind_cut_flow_fish     ) AS  ind_cut_flow_fish     ,                                         ";
		sql  += " SUM ( ind_cut_flow_landfill ) AS  ind_cut_flow_landfill ,                                         ";
		sql  += " SUM ( ind_cut_BOD_sum       ) AS  ind_cut_BOD_sum       ,                                         ";
		sql  += " SUM ( ind_cut_BOD_pop       ) AS  ind_cut_BOD_pop       ,                                         ";
		sql  += " SUM ( ind_cut_BOD_ani       ) AS  ind_cut_BOD_ani       ,                                         ";
		sql  += " SUM ( ind_cut_BOD_ind       ) AS  ind_cut_BOD_ind       ,                                         ";
		sql  += " SUM ( ind_cut_BOD_land      ) AS  ind_cut_BOD_land      ,                                         ";
		sql  += " SUM ( ind_cut_BOD_fish      ) AS  ind_cut_BOD_fish      ,                                         ";
		sql  += " SUM ( ind_cut_BOD_landfill  ) AS  ind_cut_BOD_landfill  ,                                         ";
		sql  += " SUM ( ind_cut_TN_sum        ) AS  ind_cut_TN_sum        ,                                         ";
		sql  += " SUM ( ind_cut_TN_pop        ) AS  ind_cut_TN_pop        ,                                         ";
		sql  += " SUM ( ind_cut_TN_ani        ) AS  ind_cut_TN_ani        ,                                         ";
		sql  += " SUM ( ind_cut_TN_ind        ) AS  ind_cut_TN_ind        ,                                         ";
		sql  += " SUM ( ind_cut_TN_land       ) AS  ind_cut_TN_land       ,                                         ";
		sql  += " SUM ( ind_cut_TN_fish       ) AS  ind_cut_TN_fish       ,                                         ";
		sql  += " SUM ( ind_cut_TN_landfill   ) AS  ind_cut_TN_landfill   ,                                         ";
		sql  += " SUM ( ind_cut_TP_sum        ) AS  ind_cut_TP_sum        ,                                         ";
		sql  += " SUM ( ind_cut_TP_pop        ) AS  ind_cut_TP_pop        ,                                         ";
		sql  += " SUM ( ind_cut_TP_ani        ) AS  ind_cut_TP_ani        ,                                         ";
		sql  += " SUM ( ind_cut_TP_ind        ) AS  ind_cut_TP_ind        ,                                         ";
		sql  += " SUM ( ind_cut_TP_land       ) AS  ind_cut_TP_land       ,                                         ";
		sql  += " SUM ( ind_cut_TP_fish       ) AS  ind_cut_TP_fish       ,                                         ";
		sql  += " SUM ( ind_cut_TP_landfill   ) AS  ind_cut_TP_landfill   ,                                         ";
		sql  += " SUM ( pit_in_flow_sum       ) AS  pit_in_flow_sum       ,                                         ";
		sql  += " SUM ( pit_in_flow_pop       ) AS  pit_in_flow_pop       ,                                         ";
		sql  += " SUM ( pit_in_flow_ani       ) AS  pit_in_flow_ani       ,                                         ";
		sql  += " SUM ( pit_in_flow_ind       ) AS  pit_in_flow_ind       ,                                         ";
		sql  += " SUM ( pit_in_flow_land      ) AS  pit_in_flow_land      ,                                         ";
		sql  += " SUM ( pit_in_flow_fish      ) AS  pit_in_flow_fish      ,                                         ";
		sql  += " SUM ( pit_in_flow_landfill  ) AS  pit_in_flow_landfill  ,                                         ";
		sql  += " SUM ( pit_in_BOD_sum        ) AS  pit_in_BOD_sum        ,                                         ";
		sql  += " SUM ( pit_in_BOD_pop        ) AS  pit_in_BOD_pop        ,                                         ";
		sql  += " SUM ( pit_in_BOD_ani        ) AS  pit_in_BOD_ani        ,                                         ";
		sql  += " SUM ( pit_in_BOD_ind        ) AS  pit_in_BOD_ind        ,                                         ";
		sql  += " SUM ( pit_in_BOD_land       ) AS  pit_in_BOD_land       ,                                         ";
		sql  += " SUM ( pit_in_BOD_fish       ) AS  pit_in_BOD_fish       ,                                         ";
		sql  += " SUM ( pit_in_BOD_landfill   ) AS  pit_in_BOD_landfill   ,                                         ";
		sql  += " SUM ( pit_in_TN_sum         ) AS  pit_in_TN_sum         ,                                         ";
		sql  += " SUM ( pit_in_TN_pop         ) AS  pit_in_TN_pop         ,                                         ";
		sql  += " SUM ( pit_in_TN_ani         ) AS  pit_in_TN_ani         ,                                         ";
		sql  += " SUM ( pit_in_TN_ind         ) AS  pit_in_TN_ind         ,                                         ";
		sql  += " SUM ( pit_in_TN_land        ) AS  pit_in_TN_land        ,                                         ";
		sql  += " SUM ( pit_in_TN_fish        ) AS  pit_in_TN_fish        ,                                         ";
		sql  += " SUM ( pit_in_TN_landfill    ) AS  pit_in_TN_landfill    ,                                         ";
		sql  += " SUM ( pit_in_TP_sum         ) AS  pit_in_TP_sum         ,                                         ";
		sql  += " SUM ( pit_in_TP_pop         ) AS  pit_in_TP_pop         ,                                         ";
		sql  += " SUM ( pit_in_TP_ani         ) AS  pit_in_TP_ani         ,                                         ";
		sql  += " SUM ( pit_in_TP_ind         ) AS  pit_in_TP_ind         ,                                         ";
		sql  += " SUM ( pit_in_TP_land        ) AS  pit_in_TP_land        ,                                         ";
		sql  += " SUM ( pit_in_TP_fish        ) AS  pit_in_TP_fish        ,                                         ";
		sql  += " SUM ( pit_in_TP_landfill    ) AS  pit_in_TP_landfill    ,                                         ";
		sql  += " SUM ( ind_out_flow_pop      ) AS  ind_out_flow_pop      ,                                         ";
		sql  += " SUM ( ind_out_flow_ani      ) AS  ind_out_flow_ani      ,                                         ";
		sql  += " SUM ( ind_out_flow_ind      ) AS  ind_out_flow_ind      ,                                         ";
		sql  += " SUM ( ind_out_flow_land     ) AS  ind_out_flow_land     ,                                         ";
		sql  += " SUM ( ind_out_flow_fish     ) AS  ind_out_flow_fish     ,                                         ";
		sql  += " SUM ( ind_out_flow_landfill ) AS  ind_out_flow_landfill ,                                         ";
		sql  += " SUM ( ind_out_BOD_pop       ) AS  ind_out_BOD_pop       ,                                         ";
		sql  += " SUM ( ind_out_BOD_ani       ) AS  ind_out_BOD_ani       ,                                         ";
		sql  += " SUM ( ind_out_BOD_ind       ) AS  ind_out_BOD_ind       ,                                         ";
		sql  += " SUM ( ind_out_BOD_land      ) AS  ind_out_BOD_land      ,                                         ";
		sql  += " SUM ( ind_out_BOD_fish      ) AS  ind_out_BOD_fish      ,                                         ";
		sql  += " SUM ( ind_out_BOD_landfill  ) AS  ind_out_BOD_landfill  ,                                         ";
		sql  += " SUM ( ind_out_TN_pop        ) AS  ind_out_TN_pop        ,                                         ";
		sql  += " SUM ( ind_out_TN_ani        ) AS  ind_out_TN_ani        ,                                         ";
		sql  += " SUM ( ind_out_TN_ind        ) AS  ind_out_TN_ind        ,                                         ";
		sql  += " SUM ( ind_out_TN_land       ) AS  ind_out_TN_land       ,                                         ";
		sql  += " SUM ( ind_out_TN_fish       ) AS  ind_out_TN_fish       ,                                         ";
		sql  += " SUM ( ind_out_TN_landfill   ) AS  ind_out_TN_landfill   ,                                         ";
		sql  += " SUM ( ind_out_TP_pop        ) AS  ind_out_TP_pop        ,                                         ";
		sql  += " SUM ( ind_out_TP_ani        ) AS  ind_out_TP_ani        ,                                         ";
		sql  += " SUM ( ind_out_TP_ind        ) AS  ind_out_TP_ind        ,                                         ";
		sql  += " SUM ( ind_out_TP_land       ) AS  ind_out_TP_land       ,                                         ";
		sql  += " SUM ( ind_out_TP_fish       ) AS  ind_out_TP_fish       ,                                         ";
		sql  += " SUM ( ind_out_TP_landfill   ) AS  ind_out_TP_landfill   ,                                         ";
		sql  += " SUM ( pit_out_flow_sum      ) AS  pit_out_flow_sum      ,                                         ";
		sql  += " SUM ( pit_out_flow_pop      ) AS  pit_out_flow_pop      ,                                         ";
		sql  += " SUM ( pit_out_flow_ani      ) AS  pit_out_flow_ani      ,                                         ";
		sql  += " SUM ( pit_out_flow_ind      ) AS  pit_out_flow_ind      ,                                         ";
		sql  += " SUM ( pit_out_flow_land     ) AS  pit_out_flow_land     ,                                         ";
		sql  += " SUM ( pit_out_flow_fish     ) AS  pit_out_flow_fish     ,                                         ";
		sql  += " SUM ( pit_out_flow_landfill ) AS  pit_out_flow_landfill ,                                         ";
		sql  += " SUM ( pit_out_BOD_sum       ) AS  pit_out_BOD_sum       ,                                         ";
		sql  += " SUM ( pit_out_BOD_pop       ) AS  pit_out_BOD_pop       ,                                         ";
		sql  += " SUM ( pit_out_BOD_ani       ) AS  pit_out_BOD_ani       ,                                         ";
		sql  += " SUM ( pit_out_BOD_ind       ) AS  pit_out_BOD_ind       ,                                         ";
		sql  += " SUM ( pit_out_BOD_land      ) AS  pit_out_BOD_land      ,                                         ";
		sql  += " SUM ( pit_out_BOD_fish      ) AS  pit_out_BOD_fish      ,                                         ";
		sql  += " SUM ( pit_out_BOD_landfill  ) AS  pit_out_BOD_landfill  ,                                         ";
		sql  += " SUM ( pit_out_TN_sum        ) AS  pit_out_TN_sum        ,                                         ";
		sql  += " SUM ( pit_out_TN_pop        ) AS  pit_out_TN_pop        ,                                         ";
		sql  += " SUM ( pit_out_TN_ani        ) AS  pit_out_TN_ani        ,                                         ";
		sql  += " SUM ( pit_out_TN_ind        ) AS  pit_out_TN_ind        ,                                         ";
		sql  += " SUM ( pit_out_TN_land       ) AS  pit_out_TN_land       ,                                         ";
		sql  += " SUM ( pit_out_TN_fish       ) AS  pit_out_TN_fish       ,                                         ";
		sql  += " SUM ( pit_out_TN_landfill   ) AS  pit_out_TN_landfill   ,                                         ";
		sql  += " SUM ( pit_out_TP_sum        ) AS  pit_out_TP_sum        ,                                         ";
		sql  += " SUM ( pit_out_TP_pop        ) AS  pit_out_TP_pop        ,                                         ";
		sql  += " SUM ( pit_out_TP_ani        ) AS  pit_out_TP_ani        ,                                         ";
		sql  += " SUM ( pit_out_TP_ind        ) AS  pit_out_TP_ind        ,                                         ";
		sql  += " SUM ( pit_out_TP_land       ) AS  pit_out_TP_land       ,                                         ";
		sql  += " SUM ( pit_out_TP_fish       ) AS  pit_out_TP_fish       ,                                         ";
		sql  += " SUM ( pit_out_TP_landfill   ) AS  pit_out_TP_landfill   ,                                         ";
		sql  += " SUM ( dis_flow_sum          ) AS  dis_flow_sum          ,                                         ";
		sql  += " SUM ( dis_flow_pop          ) AS  dis_flow_pop          ,                                         ";
		sql  += " SUM ( dis_flow_ani          ) AS  dis_flow_ani          ,                                         ";
		sql  += " SUM ( dis_flow_ind          ) AS  dis_flow_ind          ,                                         ";
		sql  += " SUM ( dis_flow_land         ) AS  dis_flow_land         ,                                         ";
		sql  += " SUM ( dis_flow_fish         ) AS  dis_flow_fish         ,                                         ";
		sql  += " SUM ( dis_flow_landfill     ) AS  dis_flow_landfill     ,                                         ";
		sql  += " SUM ( dis_BOD_sum           ) AS  dis_BOD_sum           ,                                         ";
		sql  += " SUM ( dis_BOD_pop           ) AS  dis_BOD_pop           ,                                         ";
		sql  += " SUM ( dis_BOD_ani           ) AS  dis_BOD_ani           ,                                         ";
		sql  += " SUM ( dis_BOD_ind           ) AS  dis_BOD_ind           ,                                         ";
		sql  += " SUM ( dis_BOD_land          ) AS  dis_BOD_land          ,                                         ";
		sql  += " SUM ( dis_BOD_fish          ) AS  dis_BOD_fish          ,                                         ";
		sql  += " SUM ( dis_BOD_landfill      ) AS  dis_BOD_landfill      ,                                         ";
		sql  += " SUM ( dis_TN_sum            ) AS  dis_TN_sum            ,                                         ";
		sql  += " SUM ( dis_TN_pop            ) AS  dis_TN_pop            ,                                         ";
		sql  += " SUM ( dis_TN_ani            ) AS  dis_TN_ani            ,                                         ";
		sql  += " SUM ( dis_TN_ind            ) AS  dis_TN_ind            ,                                         ";
		sql  += " SUM ( dis_TN_land           ) AS  dis_TN_land           ,                                         ";
		sql  += " SUM ( dis_TN_fish           ) AS  dis_TN_fish           ,                                         ";
		sql  += " SUM ( dis_TN_landfill       ) AS  dis_TN_landfill       ,                                         ";
		sql  += " SUM ( dis_TP_sum            ) AS  dis_TP_sum            ,                                         ";
		sql  += " SUM ( dis_TP_pop            ) AS  dis_TP_pop            ,                                         ";
		sql  += " SUM ( dis_TP_ani            ) AS  dis_TP_ani            ,                                         ";
		sql  += " SUM ( dis_TP_ind            ) AS  dis_TP_ind            ,                                         ";
		sql  += " SUM ( dis_TP_land           ) AS  dis_TP_land           ,                                         ";
		sql  += " SUM ( dis_TP_fish           ) AS  dis_TP_fish           ,                                         ";
		sql  += " SUM ( dis_TP_landfill       ) AS  dis_TP_landfill       ,                                         ";
		sql  += " SUM ( out_flow_sum          ) AS  out_flow_sum          ,                                         ";
		sql  += " SUM ( out_flow_pop          ) AS  out_flow_pop          ,                                         ";
		sql  += " SUM ( out_flow_ani          ) AS  out_flow_ani          ,                                         ";
		sql  += " SUM ( out_flow_ind          ) AS  out_flow_ind          ,                                         ";
		sql  += " SUM ( out_flow_land         ) AS  out_flow_land         ,                                         ";
		sql  += " SUM ( out_flow_fish         ) AS  out_flow_fish         ,                                         ";
		sql  += " SUM ( out_flow_landfill     ) AS  out_flow_landfill     ,                                         ";
		sql  += " SUM ( out_BOD_sum           ) AS  out_BOD_sum           ,                                         ";
		sql  += " SUM ( out_BOD_pop           ) AS  out_BOD_pop           ,                                         ";
		sql  += " SUM ( out_BOD_ani           ) AS  out_BOD_ani           ,                                         ";
		sql  += " SUM ( out_BOD_ind           ) AS  out_BOD_ind           ,                                         ";
		sql  += " SUM ( out_BOD_land          ) AS  out_BOD_land          ,                                         ";
		sql  += " SUM ( out_BOD_fish          ) AS  out_BOD_fish          ,                                         ";
		sql  += " SUM ( out_BOD_landfill      ) AS  out_BOD_landfill      ,                                         ";
		sql  += " SUM ( out_TN_sum            ) AS  out_TN_sum            ,                                         ";
		sql  += " SUM ( out_TN_pop            ) AS  out_TN_pop            ,                                         ";
		sql  += " SUM ( out_TN_ani            ) AS  out_TN_ani            ,                                         ";
		sql  += " SUM ( out_TN_ind            ) AS  out_TN_ind            ,                                         ";
		sql  += " SUM ( out_TN_land           ) AS  out_TN_land           ,                                         ";
		sql  += " SUM ( out_TN_fish           ) AS  out_TN_fish           ,                                         ";
		sql  += " SUM ( out_TN_landfill       ) AS  out_TN_landfill       ,                                         ";
		sql  += " SUM ( out_TP_sum            ) AS  out_TP_sum            ,                                         ";
		sql  += " SUM ( out_TP_pop            ) AS  out_TP_pop            ,                                         ";
		sql  += " SUM ( out_TP_ani            ) AS  out_TP_ani            ,                                         ";
		sql  += " SUM ( out_TP_ind            ) AS  out_TP_ind            ,                                         ";
		sql  += " SUM ( out_TP_land           ) AS  out_TP_land           ,                                         ";
		sql  += " SUM ( out_TP_fish           ) AS  out_TP_fish           ,                                         ";
		sql  += " SUM ( out_TP_landfill       ) AS  out_TP_landfill       ,                                         ";
		sql  += " '' AS  WS_NM                 ,                                                                    ";
		sql  += " '' AS  BASIN                  FROM POLLULANT_LOAD WHERE ADM_CD LIKE                         ";
		if(adm2 == ""){
			//query.where = "ADM_CD like '"+amdBtn1.lastValue+"%'";
			sql += " '"+adm1+"%' ";
		}else if(adm2 != "" && adm3 == ""){
			sql += " '"+adm2.substring(0,5)+"%' ";
		}else{    
			sql += " '"+adm3.substring(0,7)+"%' ";
		}
		sql  += " UNION                                                                                             ";
		sql  += " SELECT YYYY,  ADM_CD,  DO_NM,  CTY_NM,  DONG_NM ,  RI_NM,                                         ";
		sql  += " gnr_flow_sum ,                                                                         ";
		sql  += " gnr_flow_pop                    ,                                                                 ";
		sql  += " gnr_flow_ani          ,                                                                           ";
		sql  += " gnr_flow_ind          ,                                                                           ";
		sql  += " gnr_flow_land         ,                                                                           ";
		sql  += " gnr_flow_fish         ,                                                                           ";
		sql  += " gnr_flow_landfill     ,                                                                           ";
		sql  += " gnr_BOD_pop           ,                                                                           ";
		sql  += " gnr_BOD_ani           ,                                                                           ";
		sql  += " gnr_BOD_ind           ,                                                                           ";
		sql  += " gnr_BOD_land          ,                                                                           ";
		sql  += " gnr_BOD_fish          ,                                                                           ";
		sql  += " gnr_BOD_landfill      ,                                                                           ";
		sql  += " gnr_TN_pop            ,                                                                           ";
		sql  += " gnr_TN_ani            ,                                                                           ";
		sql  += " gnr_TN_ind            ,                                                                           ";
		sql  += " gnr_TN_land           ,                                                                           ";
		sql  += " gnr_TN_fish           ,                                                                           ";
		sql  += " gnr_TN_landfill       ,                                                                           ";
		sql  += " gnr_TP_pop            ,                                                                           ";
		sql  += " gnr_TP_ani            ,                                                                           ";
		sql  += " gnr_TP_ind            ,                                                                           ";
		sql  += " gnr_TP_land           ,                                                                           ";
		sql  += " gnr_TP_fish           ,                                                                           ";
		sql  += " gnr_TP_landfill       ,                                                                           ";
		sql  += " drt_flow_sum          ,                                                                           ";
		sql  += " drt_flow_pop          ,                                                                           ";
		sql  += " drt_flow_ani          ,                                                                           ";
		sql  += " drt_flow_ind          ,                                                                           ";
		sql  += " drt_flow_land         ,                                                                           ";
		sql  += " drt_flow_fish         ,                                                                           ";
		sql  += " drt_flow_landfill     ,                                                                           ";
		sql  += " drt_BOD_sum           ,                                                                           ";
		sql  += " drt_BOD_pop           ,                                                                           ";
		sql  += " drt_BOD_ani           ,                                                                           ";
		sql  += " drt_BOD_ind           ,                                                                           ";
		sql  += " drt_BOD_land          ,                                                                           ";
		sql  += " drt_BOD_fish          ,                                                                           ";
		sql  += " drt_BOD_landfill      ,                                                                           ";
		sql  += " drt_TN_sum            ,                                                                           ";
		sql  += " drt_TN_pop            ,                                                                           ";
		sql  += " drt_TN_ani            ,                                                                           ";
		sql  += " drt_TN_ind            ,                                                                           ";
		sql  += " drt_TN_land           ,                                                                           ";
		sql  += " drt_TN_fish           ,                                                                           ";
		sql  += " drt_TN_landfill       ,                                                                           ";
		sql  += " drt_TP_sum            ,                                                                           ";
		sql  += " drt_TP_pop            ,                                                                           ";
		sql  += " drt_TP_ani            ,                                                                           ";
		sql  += " drt_TP_ind            ,                                                                           ";
		sql  += " drt_TP_land           ,                                                                           ";
		sql  += " drt_TP_fish           ,                                                                           ";
		sql  += " drt_TP_landfill       ,                                                                           ";
		sql  += " ind_cut_flow_sum      ,                                                                           ";
		sql  += " ind_cut_flow_pop      ,                                                                           ";
		sql  += " ind_cut_flow_ani      ,                                                                           ";
		sql  += " ind_cut_flow_ind      ,                                                                           ";
		sql  += " ind_cut_flow_land     ,                                                                           ";
		sql  += " ind_cut_flow_fish     ,                                                                           ";
		sql  += " ind_cut_flow_landfill ,                                                                           ";
		sql  += " ind_cut_BOD_sum       ,                                                                           ";
		sql  += " ind_cut_BOD_pop       ,                                                                           ";
		sql  += " ind_cut_BOD_ani       ,                                                                           ";
		sql  += " ind_cut_BOD_ind       ,                                                                           ";
		sql  += " ind_cut_BOD_land      ,                                                                           ";
		sql  += " ind_cut_BOD_fish      ,                                                                           ";
		sql  += " ind_cut_BOD_landfill  ,                                                                           ";
		sql  += " ind_cut_TN_sum        ,                                                                           ";
		sql  += " ind_cut_TN_pop        ,                                                                           ";
		sql  += " ind_cut_TN_ani        ,                                                                           ";
		sql  += " ind_cut_TN_ind        ,                                                                           ";
		sql  += " ind_cut_TN_land       ,                                                                           ";
		sql  += " ind_cut_TN_fish       ,                                                                           ";
		sql  += " ind_cut_TN_landfill   ,                                                                           ";
		sql  += " ind_cut_TP_sum        ,                                                                           ";
		sql  += " ind_cut_TP_pop        ,                                                                           ";
		sql  += " ind_cut_TP_ani        ,                                                                           ";
		sql  += " ind_cut_TP_ind        ,                                                                           ";
		sql  += " ind_cut_TP_land       ,                                                                           ";
		sql  += " ind_cut_TP_fish       ,                                                                           ";
		sql  += " ind_cut_TP_landfill   ,                                                                           ";
		sql  += " pit_in_flow_sum       ,                                                                           ";
		sql  += " pit_in_flow_pop       ,                                                                           ";
		sql  += " pit_in_flow_ani       ,                                                                           ";
		sql  += " pit_in_flow_ind       ,                                                                           ";
		sql  += " pit_in_flow_land      ,                                                                           ";
		sql  += " pit_in_flow_fish      ,                                                                           ";
		sql  += " pit_in_flow_landfill  ,                                                                           ";
		sql  += " pit_in_BOD_sum        ,                                                                           ";
		sql  += " pit_in_BOD_pop        ,                                                                           ";
		sql  += " pit_in_BOD_ani        ,                                                                           ";
		sql  += " pit_in_BOD_ind        ,                                                                           ";
		sql  += " pit_in_BOD_land       ,                                                                           ";
		sql  += " pit_in_BOD_fish       ,                                                                           ";
		sql  += " pit_in_BOD_landfill   ,                                                                           ";
		sql  += " pit_in_TN_sum         ,                                                                           ";
		sql  += " pit_in_TN_pop         ,                                                                           ";
		sql  += " pit_in_TN_ani         ,                                                                           ";
		sql  += " pit_in_TN_ind         ,                                                                           ";
		sql  += " pit_in_TN_land        ,                                                                           ";
		sql  += " pit_in_TN_fish        ,                                                                           ";
		sql  += " pit_in_TN_landfill    ,                                                                           ";
		sql  += " pit_in_TP_sum         ,                                                                           ";
		sql  += " pit_in_TP_pop         ,                                                                           ";
		sql  += " pit_in_TP_ani         ,                                                                           ";
		sql  += " pit_in_TP_ind         ,                                                                           ";
		sql  += " pit_in_TP_land        ,                                                                           ";
		sql  += " pit_in_TP_fish        ,                                                                           ";
		sql  += " pit_in_TP_landfill    ,                                                                           ";
		sql  += " ind_out_flow_pop      ,                                                                           ";
		sql  += " ind_out_flow_ani      ,                                                                           ";
		sql  += " ind_out_flow_ind      ,                                                                           ";
		sql  += " ind_out_flow_land     ,                                                                           ";
		sql  += " ind_out_flow_fish     ,                                                                           ";
		sql  += " ind_out_flow_landfill ,                                                                           ";
		sql  += " ind_out_BOD_pop       ,                                                                           ";
		sql  += " ind_out_BOD_ani       ,                                                                           ";
		sql  += " ind_out_BOD_ind       ,                                                                           ";
		sql  += " ind_out_BOD_land      ,                                                                           ";
		sql  += " ind_out_BOD_fish      ,                                                                           ";
		sql  += " ind_out_BOD_landfill  ,                                                                           ";
		sql  += " ind_out_TN_pop        ,                                                                           ";
		sql  += " ind_out_TN_ani        ,                                                                           ";
		sql  += " ind_out_TN_ind        ,                                                                           ";
		sql  += " ind_out_TN_land       ,                                                                           ";
		sql  += " ind_out_TN_fish       ,                                                                           ";
		sql  += " ind_out_TN_landfill   ,                                                                           ";
		sql  += " ind_out_TP_pop        ,                                                                           ";
		sql  += " ind_out_TP_ani        ,                                                                           ";
		sql  += " ind_out_TP_ind        ,                                                                           ";
		sql  += " ind_out_TP_land       ,                                                                           ";
		sql  += " ind_out_TP_fish       ,                                                                           ";
		sql  += " ind_out_TP_landfill   ,                                                                           ";
		sql  += " pit_out_flow_sum      ,                                                                           ";
		sql  += " pit_out_flow_pop      ,                                                                           ";
		sql  += " pit_out_flow_ani      ,                                                                           ";
		sql  += " pit_out_flow_ind      ,                                                                           ";
		sql  += " pit_out_flow_land     ,                                                                           ";
		sql  += " pit_out_flow_fish     ,                                                                           ";
		sql  += " pit_out_flow_landfill ,                                                                           ";
		sql  += " pit_out_BOD_sum       ,                                                                           ";
		sql  += " pit_out_BOD_pop       ,                                                                           ";
		sql  += " pit_out_BOD_ani       ,                                                                           ";
		sql  += " pit_out_BOD_ind       ,                                                                           ";
		sql  += " pit_out_BOD_land      ,                                                                           ";
		sql  += " pit_out_BOD_fish      ,                                                                           ";
		sql  += " pit_out_BOD_landfill  ,                                                                           ";
		sql  += " pit_out_TN_sum        ,                                                                           ";
		sql  += " pit_out_TN_pop        ,                                                                           ";
		sql  += " pit_out_TN_ani        ,                                                                           ";
		sql  += " pit_out_TN_ind        ,                                                                           ";
		sql  += " pit_out_TN_land       ,                                                                           ";
		sql  += " pit_out_TN_fish       ,                                                                           ";
		sql  += " pit_out_TN_landfill   ,                                                                           ";
		sql  += " pit_out_TP_sum        ,                                                                           ";
		sql  += " pit_out_TP_pop        ,                                                                           ";
		sql  += " pit_out_TP_ani        ,                                                                           ";
		sql  += " pit_out_TP_ind        ,                                                                           ";
		sql  += " pit_out_TP_land       ,                                                                           ";
		sql  += " pit_out_TP_fish       ,                                                                           ";
		sql  += " pit_out_TP_landfill   ,                                                                           ";
		sql  += " dis_flow_sum          ,                                                                           ";
		sql  += " dis_flow_pop          ,                                                                           ";
		sql  += " dis_flow_ani          ,                                                                           ";
		sql  += " dis_flow_ind          ,                                                                           ";
		sql  += " dis_flow_land         ,                                                                           ";
		sql  += " dis_flow_fish         ,                                                                           ";
		sql  += " dis_flow_landfill     ,                                                                           ";
		sql  += " dis_BOD_sum           ,                                                                           ";
		sql  += " dis_BOD_pop           ,                                                                           ";
		sql  += " dis_BOD_ani           ,                                                                           ";
		sql  += " dis_BOD_ind           ,                                                                           ";
		sql  += " dis_BOD_land          ,                                                                           ";
		sql  += " dis_BOD_fish          ,                                                                           ";
		sql  += " dis_BOD_landfill      ,                                                                           ";
		sql  += " dis_TN_sum            ,                                                                           ";
		sql  += " dis_TN_pop            ,                                                                           ";
		sql  += " dis_TN_ani            ,                                                                           ";
		sql  += " dis_TN_ind            ,                                                                           ";
		sql  += " dis_TN_land           ,                                                                           ";
		sql  += " dis_TN_fish           ,                                                                           ";
		sql  += " dis_TN_landfill       ,                                                                           ";
		sql  += " dis_TP_sum            ,                                                                           ";
		sql  += " dis_TP_pop            ,                                                                           ";
		sql  += " dis_TP_ani            ,                                                                           ";
		sql  += " dis_TP_ind            ,                                                                           ";
		sql  += " dis_TP_land           ,                                                                           ";
		sql  += " dis_TP_fish           ,                                                                           ";
		sql  += " dis_TP_landfill       ,                                                                           ";
		sql  += " out_flow_sum          ,                                                                           ";
		sql  += " out_flow_pop          ,                                                                           ";
		sql  += " out_flow_ani          ,                                                                           ";
		sql  += " out_flow_ind          ,                                                                           ";
		sql  += " out_flow_land         ,                                                                           ";
		sql  += " out_flow_fish         ,                                                                           ";
		sql  += " out_flow_landfill     ,                                                                           ";
		sql  += " out_BOD_sum           ,                                                                           ";
		sql  += " out_BOD_pop           ,                                                                           ";
		sql  += " out_BOD_ani           ,                                                                           ";
		sql  += " out_BOD_ind           ,                                                                           ";
		sql  += " out_BOD_land          ,                                                                           ";
		sql  += " out_BOD_fish          ,                                                                           ";
		sql  += " out_BOD_landfill      ,                                                                           ";
		sql  += " out_TN_sum            ,                                                                           ";
		sql  += " out_TN_pop            ,                                                                           ";
		sql  += " out_TN_ani            ,                                                                           ";
		sql  += " out_TN_ind            ,                                                                           ";
		sql  += " out_TN_land           ,                                                                           ";
		sql  += " out_TN_fish           ,                                                                           ";
		sql  += " out_TN_landfill       ,                                                                           ";
		sql  += " out_TP_sum            ,                                                                           ";
		sql  += " out_TP_pop            ,                                                                           ";
		sql  += " out_TP_ani            ,                                                                           ";
		sql  += " out_TP_ind            ,                                                                           ";
		sql  += " out_TP_land           ,                                                                           ";
		sql  += " out_TP_fish           ,                                                                           ";
		sql  += " out_TP_landfill       ,                                                                           ";
		sql  += " WS_NM                 ,                                                                           ";
		sql  += " BASIN  FROM         POLLULANT_LOAD WHERE ADM_CD LIKE	";
		
		if(adm2 == ""){
			//query.where = "ADM_CD like '"+amdBtn1.lastValue+"%'";
			sql += " '"+adm1+"%' ";
		}else if(adm2 != "" && adm3 == ""){
			sql += " '"+adm2.substring(0,5)+"%' ";
		}else{    
			sql += " '"+adm3.substring(0,7)+"%' ";
		}
		sql  += " ORDER BY YYYY DESC 
	
	
		
   //out.print(sql);
   //System.out.println(sql);
   stmt = con.createStatement();
   rs = stmt.executeQuery(sql);
   
	JSONObject jsonObj  = new JSONObject();
	JSONArray jsonArr = new JSONArray();
	JSONObject jsonRecord = null;
	
	while(rs.next()) {
		jsonRecord = new JSONObject();

		jsonRecord.put("YYYY",rs.getString("YYYY"));
		jsonRecord.put("ADM_CD",rs.getString("ADM_CD"));
		jsonRecord.put("DO_NM",rs.getString("DO_NM"));
		jsonRecord.put("CTY_NM",rs.getString("CTY_NM"));
		jsonRecord.put("DONG_NM",rs.getString("DONG_NM"));
		jsonRecord.put("RI_NM",rs.getString("RI_NM"));
		jsonRecord.put("GNR_FLOW_SUM",rs.getString("GNR_FLOW_SUM"));
		jsonRecord.put("GNR_FLOW_POP",rs.getString("GNR_FLOW_POP"));
		jsonRecord.put("GNR_FLOW_ANI",rs.getString("GNR_FLOW_ANI"));
		jsonRecord.put("GNR_FLOW_IND",rs.getString("GNR_FLOW_IND"));
		jsonRecord.put("GNR_FLOW_LAND",rs.getString("GNR_FLOW_LAND"));
		jsonRecord.put("GNR_FLOW_FISH",rs.getString("GNR_FLOW_FISH"));
		jsonRecord.put("GNR_FLOW_LANDFILL",rs.getString("GNR_FLOW_LANDFILL"));
		jsonRecord.put("GNR_BOD_POP",rs.getString("GNR_BOD_POP"));
		jsonRecord.put("GNR_BOD_ANI",rs.getString("GNR_BOD_ANI"));
		jsonRecord.put("GNR_BOD_IND",rs.getString("GNR_BOD_IND"));
		jsonRecord.put("GNR_BOD_LAND",rs.getString("GNR_BOD_LAND"));
		jsonRecord.put("GNR_BOD_FISH",rs.getString("GNR_BOD_FISH"));
		jsonRecord.put("GNR_BOD_LANDFILL",rs.getString("GNR_BOD_LANDFILL"));
		jsonRecord.put("GNR_TN_POP",rs.getString("GNR_TN_POP"));
		jsonRecord.put("GNR_TN_ANI",rs.getString("GNR_TN_ANI"));
		jsonRecord.put("GNR_TN_IND",rs.getString("GNR_TN_IND"));
		jsonRecord.put("GNR_TN_LAND",rs.getString("GNR_TN_LAND"));
		jsonRecord.put("GNR_TN_FISH",rs.getString("GNR_TN_FISH"));
		jsonRecord.put("GNR_TN_LANDFILL",rs.getString("GNR_TN_LANDFILL"));
		jsonRecord.put("GNR_TP_POP",rs.getString("GNR_TP_POP"));
		jsonRecord.put("GNR_TP_ANI",rs.getString("GNR_TP_ANI"));
		jsonRecord.put("GNR_TP_IND",rs.getString("GNR_TP_IND"));
		jsonRecord.put("GNR_TP_LAND",rs.getString("GNR_TP_LAND"));
		jsonRecord.put("GNR_TP_FISH",rs.getString("GNR_TP_FISH"));
		jsonRecord.put("GNR_TP_LANDFILL",rs.getString("GNR_TP_LANDFILL"));
		jsonRecord.put("DRT_FLOW_SUM",rs.getString("DRT_FLOW_SUM"));
		jsonRecord.put("DRT_FLOW_POP",rs.getString("DRT_FLOW_POP"));
		jsonRecord.put("DRT_FLOW_ANI",rs.getString("DRT_FLOW_ANI"));
		jsonRecord.put("DRT_FLOW_IND",rs.getString("DRT_FLOW_IND"));
		jsonRecord.put("DRT_FLOW_LAND",rs.getString("DRT_FLOW_LAND"));
		jsonRecord.put("DRT_FLOW_FISH",rs.getString("DRT_FLOW_FISH"));
		jsonRecord.put("DRT_FLOW_LANDFILL",rs.getString("DRT_FLOW_LANDFILL"));
		jsonRecord.put("DRT_BOD_SUM",rs.getString("DRT_BOD_SUM"));
		jsonRecord.put("DRT_BOD_POP",rs.getString("DRT_BOD_POP"));
		jsonRecord.put("DRT_BOD_ANI",rs.getString("DRT_BOD_ANI"));
		jsonRecord.put("DRT_BOD_IND",rs.getString("DRT_BOD_IND"));
		jsonRecord.put("DRT_BOD_LAND",rs.getString("DRT_BOD_LAND"));
		jsonRecord.put("DRT_BOD_FISH",rs.getString("DRT_BOD_FISH"));
		jsonRecord.put("DRT_BOD_LANDFILL",rs.getString("DRT_BOD_LANDFILL"));
		jsonRecord.put("DRT_TN_SUM",rs.getString("DRT_TN_SUM"));
		jsonRecord.put("DRT_TN_POP",rs.getString("DRT_TN_POP"));
		jsonRecord.put("DRT_TN_ANI",rs.getString("DRT_TN_ANI"));
		jsonRecord.put("DRT_TN_IND",rs.getString("DRT_TN_IND"));
		jsonRecord.put("DRT_TN_LAND",rs.getString("DRT_TN_LAND"));
		jsonRecord.put("DRT_TN_FISH",rs.getString("DRT_TN_FISH"));
		jsonRecord.put("DRT_TN_LANDFILL",rs.getString("DRT_TN_LANDFILL"));
		jsonRecord.put("DRT_TP_SUM",rs.getString("DRT_TP_SUM"));
		jsonRecord.put("DRT_TP_POP",rs.getString("DRT_TP_POP"));
		jsonRecord.put("DRT_TP_ANI",rs.getString("DRT_TP_ANI"));
		jsonRecord.put("DRT_TP_IND",rs.getString("DRT_TP_IND"));
		jsonRecord.put("DRT_TP_LAND",rs.getString("DRT_TP_LAND"));
		jsonRecord.put("DRT_TP_FISH",rs.getString("DRT_TP_FISH"));
		jsonRecord.put("DRT_TP_LANDFILL",rs.getString("DRT_TP_LANDFILL"));
		jsonRecord.put("IND_CUT_FLOW_SUM",rs.getString("IND_CUT_FLOW_SUM"));
		jsonRecord.put("IND_CUT_FLOW_POP",rs.getString("IND_CUT_FLOW_POP"));
		jsonRecord.put("IND_CUT_FLOW_ANI",rs.getString("IND_CUT_FLOW_ANI"));
		jsonRecord.put("IND_CUT_FLOW_IND",rs.getString("IND_CUT_FLOW_IND"));
		jsonRecord.put("IND_CUT_FLOW_LAND",rs.getString("IND_CUT_FLOW_LAND"));
		jsonRecord.put("IND_CUT_FLOW_FISH",rs.getString("IND_CUT_FLOW_FISH"));
		jsonRecord.put("IND_CUT_FLOW_LANDFILL",rs.getString("IND_CUT_FLOW_LANDFILL"));
		jsonRecord.put("IND_CUT_BOD_SUM",rs.getString("IND_CUT_BOD_SUM"));
		jsonRecord.put("IND_CUT_BOD_POP",rs.getString("IND_CUT_BOD_POP"));
		jsonRecord.put("IND_CUT_BOD_ANI",rs.getString("IND_CUT_BOD_ANI"));
		jsonRecord.put("IND_CUT_BOD_IND",rs.getString("IND_CUT_BOD_IND"));
		jsonRecord.put("IND_CUT_BOD_LAND",rs.getString("IND_CUT_BOD_LAND"));
		jsonRecord.put("IND_CUT_BOD_FISH",rs.getString("IND_CUT_BOD_FISH"));
		jsonRecord.put("IND_CUT_BOD_LANDFILL",rs.getString("IND_CUT_BOD_LANDFILL"));
		jsonRecord.put("IND_CUT_TN_SUM",rs.getString("IND_CUT_TN_SUM"));
		jsonRecord.put("IND_CUT_TN_POP",rs.getString("IND_CUT_TN_POP"));
		jsonRecord.put("IND_CUT_TN_ANI",rs.getString("IND_CUT_TN_ANI"));
		jsonRecord.put("IND_CUT_TN_IND",rs.getString("IND_CUT_TN_IND"));
		jsonRecord.put("IND_CUT_TN_LAND",rs.getString("IND_CUT_TN_LAND"));
		jsonRecord.put("IND_CUT_TN_FISH",rs.getString("IND_CUT_TN_FISH"));
		jsonRecord.put("IND_CUT_TN_LANDFILL",rs.getString("IND_CUT_TN_LANDFILL"));
		jsonRecord.put("IND_CUT_TP_SUM",rs.getString("IND_CUT_TP_SUM"));
		jsonRecord.put("IND_CUT_TP_POP",rs.getString("IND_CUT_TP_POP"));
		jsonRecord.put("IND_CUT_TP_ANI",rs.getString("IND_CUT_TP_ANI"));
		jsonRecord.put("IND_CUT_TP_IND",rs.getString("IND_CUT_TP_IND"));
		jsonRecord.put("IND_CUT_TP_LAND",rs.getString("IND_CUT_TP_LAND"));
		jsonRecord.put("IND_CUT_TP_FISH",rs.getString("IND_CUT_TP_FISH"));
		jsonRecord.put("IND_CUT_TP_LANDFILL",rs.getString("IND_CUT_TP_LANDFILL"));
		jsonRecord.put("PIT_IN_FLOW_SUM",rs.getString("PIT_IN_FLOW_SUM"));
		jsonRecord.put("PIT_IN_FLOW_POP",rs.getString("PIT_IN_FLOW_POP"));
		jsonRecord.put("PIT_IN_FLOW_ANI",rs.getString("PIT_IN_FLOW_ANI"));
		jsonRecord.put("PIT_IN_FLOW_IND",rs.getString("PIT_IN_FLOW_IND"));
		jsonRecord.put("PIT_IN_FLOW_LAND",rs.getString("PIT_IN_FLOW_LAND"));
		jsonRecord.put("PIT_IN_FLOW_FISH",rs.getString("PIT_IN_FLOW_FISH"));
		jsonRecord.put("PIT_IN_FLOW_LANDFILL",rs.getString("PIT_IN_FLOW_LANDFILL"));
		jsonRecord.put("PIT_IN_BOD_SUM",rs.getString("PIT_IN_BOD_SUM"));
		jsonRecord.put("PIT_IN_BOD_POP",rs.getString("PIT_IN_BOD_POP"));
		jsonRecord.put("PIT_IN_BOD_ANI",rs.getString("PIT_IN_BOD_ANI"));
		jsonRecord.put("PIT_IN_BOD_IND",rs.getString("PIT_IN_BOD_IND"));
		jsonRecord.put("PIT_IN_BOD_LAND",rs.getString("PIT_IN_BOD_LAND"));
		jsonRecord.put("PIT_IN_BOD_FISH",rs.getString("PIT_IN_BOD_FISH"));
		jsonRecord.put("PIT_IN_BOD_LANDFILL",rs.getString("PIT_IN_BOD_LANDFILL"));
		jsonRecord.put("PIT_IN_TN_SUM",rs.getString("PIT_IN_TN_SUM"));
		jsonRecord.put("PIT_IN_TN_POP",rs.getString("PIT_IN_TN_POP"));
		jsonRecord.put("PIT_IN_TN_ANI",rs.getString("PIT_IN_TN_ANI"));
		jsonRecord.put("PIT_IN_TN_IND",rs.getString("PIT_IN_TN_IND"));
		jsonRecord.put("PIT_IN_TN_LAND",rs.getString("PIT_IN_TN_LAND"));
		jsonRecord.put("PIT_IN_TN_FISH",rs.getString("PIT_IN_TN_FISH"));
		jsonRecord.put("PIT_IN_TN_LANDFILL",rs.getString("PIT_IN_TN_LANDFILL"));
		jsonRecord.put("PIT_IN_TP_SUM",rs.getString("PIT_IN_TP_SUM"));
		jsonRecord.put("PIT_IN_TP_POP",rs.getString("PIT_IN_TP_POP"));
		jsonRecord.put("PIT_IN_TP_ANI",rs.getString("PIT_IN_TP_ANI"));
		jsonRecord.put("PIT_IN_TP_IND",rs.getString("PIT_IN_TP_IND"));
		jsonRecord.put("PIT_IN_TP_LAND",rs.getString("PIT_IN_TP_LAND"));
		jsonRecord.put("PIT_IN_TP_FISH",rs.getString("PIT_IN_TP_FISH"));
		jsonRecord.put("PIT_IN_TP_LANDFILL",rs.getString("PIT_IN_TP_LANDFILL"));
		jsonRecord.put("IND_OUT_FLOW_POP",rs.getString("IND_OUT_FLOW_POP"));
		jsonRecord.put("IND_OUT_FLOW_ANI",rs.getString("IND_OUT_FLOW_ANI"));
		jsonRecord.put("IND_OUT_FLOW_IND",rs.getString("IND_OUT_FLOW_IND"));
		jsonRecord.put("IND_OUT_FLOW_LAND",rs.getString("IND_OUT_FLOW_LAND"));
		jsonRecord.put("IND_OUT_FLOW_FISH",rs.getString("IND_OUT_FLOW_FISH"));
		jsonRecord.put("IND_OUT_FLOW_LANDFILL",rs.getString("IND_OUT_FLOW_LANDFILL"));
		jsonRecord.put("IND_OUT_BOD_POP",rs.getString("IND_OUT_BOD_POP"));
		jsonRecord.put("IND_OUT_BOD_ANI",rs.getString("IND_OUT_BOD_ANI"));
		jsonRecord.put("IND_OUT_BOD_IND",rs.getString("IND_OUT_BOD_IND"));
		jsonRecord.put("IND_OUT_BOD_LAND",rs.getString("IND_OUT_BOD_LAND"));
		jsonRecord.put("IND_OUT_BOD_FISH",rs.getString("IND_OUT_BOD_FISH"));
		jsonRecord.put("IND_OUT_BOD_LANDFILL",rs.getString("IND_OUT_BOD_LANDFILL"));
		jsonRecord.put("IND_OUT_TN_POP",rs.getString("IND_OUT_TN_POP"));
		jsonRecord.put("IND_OUT_TN_ANI",rs.getString("IND_OUT_TN_ANI"));
		jsonRecord.put("IND_OUT_TN_IND",rs.getString("IND_OUT_TN_IND"));
		jsonRecord.put("IND_OUT_TN_LAND",rs.getString("IND_OUT_TN_LAND"));
		jsonRecord.put("IND_OUT_TN_FISH",rs.getString("IND_OUT_TN_FISH"));
		jsonRecord.put("IND_OUT_TN_LANDFILL",rs.getString("IND_OUT_TN_LANDFILL"));
		jsonRecord.put("IND_OUT_TP_POP",rs.getString("IND_OUT_TP_POP"));
		jsonRecord.put("IND_OUT_TP_ANI",rs.getString("IND_OUT_TP_ANI"));
		jsonRecord.put("IND_OUT_TP_IND",rs.getString("IND_OUT_TP_IND"));
		jsonRecord.put("IND_OUT_TP_LAND",rs.getString("IND_OUT_TP_LAND"));
		jsonRecord.put("IND_OUT_TP_FISH",rs.getString("IND_OUT_TP_FISH"));
		jsonRecord.put("IND_OUT_TP_LANDFILL",rs.getString("IND_OUT_TP_LANDFILL"));
		jsonRecord.put("PIT_OUT_FLOW_SUM",rs.getString("PIT_OUT_FLOW_SUM"));
		jsonRecord.put("PIT_OUT_FLOW_POP",rs.getString("PIT_OUT_FLOW_POP"));
		jsonRecord.put("PIT_OUT_FLOW_ANI",rs.getString("PIT_OUT_FLOW_ANI"));
		jsonRecord.put("PIT_OUT_FLOW_IND",rs.getString("PIT_OUT_FLOW_IND"));
		jsonRecord.put("PIT_OUT_FLOW_LAND",rs.getString("PIT_OUT_FLOW_LAND"));
		jsonRecord.put("PIT_OUT_FLOW_FISH",rs.getString("PIT_OUT_FLOW_FISH"));
		jsonRecord.put("PIT_OUT_FLOW_LANDFILL",rs.getString("PIT_OUT_FLOW_LANDFILL"));
		jsonRecord.put("PIT_OUT_BOD_SUM",rs.getString("PIT_OUT_BOD_SUM"));
		jsonRecord.put("PIT_OUT_BOD_POP",rs.getString("PIT_OUT_BOD_POP"));
		jsonRecord.put("PIT_OUT_BOD_ANI",rs.getString("PIT_OUT_BOD_ANI"));
		jsonRecord.put("PIT_OUT_BOD_IND",rs.getString("PIT_OUT_BOD_IND"));
		jsonRecord.put("PIT_OUT_BOD_LAND",rs.getString("PIT_OUT_BOD_LAND"));
		jsonRecord.put("PIT_OUT_BOD_FISH",rs.getString("PIT_OUT_BOD_FISH"));
		jsonRecord.put("PIT_OUT_BOD_LANDFILL",rs.getString("PIT_OUT_BOD_LANDFILL"));
		jsonRecord.put("PIT_OUT_TN_SUM",rs.getString("PIT_OUT_TN_SUM"));
		jsonRecord.put("PIT_OUT_TN_POP",rs.getString("PIT_OUT_TN_POP"));
		jsonRecord.put("PIT_OUT_TN_ANI",rs.getString("PIT_OUT_TN_ANI"));
		jsonRecord.put("PIT_OUT_TN_IND",rs.getString("PIT_OUT_TN_IND"));
		jsonRecord.put("PIT_OUT_TN_LAND",rs.getString("PIT_OUT_TN_LAND"));
		jsonRecord.put("PIT_OUT_TN_FISH",rs.getString("PIT_OUT_TN_FISH"));
		jsonRecord.put("PIT_OUT_TN_LANDFILL",rs.getString("PIT_OUT_TN_LANDFILL"));
		jsonRecord.put("PIT_OUT_TP_SUM",rs.getString("PIT_OUT_TP_SUM"));
		jsonRecord.put("PIT_OUT_TP_POP",rs.getString("PIT_OUT_TP_POP"));
		jsonRecord.put("PIT_OUT_TP_ANI",rs.getString("PIT_OUT_TP_ANI"));
		jsonRecord.put("PIT_OUT_TP_IND",rs.getString("PIT_OUT_TP_IND"));
		jsonRecord.put("PIT_OUT_TP_LAND",rs.getString("PIT_OUT_TP_LAND"));
		jsonRecord.put("PIT_OUT_TP_FISH",rs.getString("PIT_OUT_TP_FISH"));
		jsonRecord.put("PIT_OUT_TP_LANDFILL",rs.getString("PIT_OUT_TP_LANDFILL"));
		jsonRecord.put("DIS_FLOW_SUM",rs.getString("DIS_FLOW_SUM"));
		jsonRecord.put("DIS_FLOW_POP",rs.getString("DIS_FLOW_POP"));
		jsonRecord.put("DIS_FLOW_ANI",rs.getString("DIS_FLOW_ANI"));
		jsonRecord.put("DIS_FLOW_IND",rs.getString("DIS_FLOW_IND"));
		jsonRecord.put("DIS_FLOW_LAND",rs.getString("DIS_FLOW_LAND"));
		jsonRecord.put("DIS_FLOW_FISH",rs.getString("DIS_FLOW_FISH"));
		jsonRecord.put("DIS_FLOW_LANDFILL",rs.getString("DIS_FLOW_LANDFILL"));
		jsonRecord.put("DIS_BOD_SUM",rs.getString("DIS_BOD_SUM"));
		jsonRecord.put("DIS_BOD_POP",rs.getString("DIS_BOD_POP"));
		jsonRecord.put("DIS_BOD_ANI",rs.getString("DIS_BOD_ANI"));
		jsonRecord.put("DIS_BOD_IND",rs.getString("DIS_BOD_IND"));
		jsonRecord.put("DIS_BOD_LAND",rs.getString("DIS_BOD_LAND"));
		jsonRecord.put("DIS_BOD_FISH",rs.getString("DIS_BOD_FISH"));
		jsonRecord.put("DIS_BOD_LANDFILL",rs.getString("DIS_BOD_LANDFILL"));
		jsonRecord.put("DIS_TN_SUM",rs.getString("DIS_TN_SUM"));
		jsonRecord.put("DIS_TN_POP",rs.getString("DIS_TN_POP"));
		jsonRecord.put("DIS_TN_ANI",rs.getString("DIS_TN_ANI"));
		jsonRecord.put("DIS_TN_IND",rs.getString("DIS_TN_IND"));
		jsonRecord.put("DIS_TN_LAND",rs.getString("DIS_TN_LAND"));
		jsonRecord.put("DIS_TN_FISH",rs.getString("DIS_TN_FISH"));
		jsonRecord.put("DIS_TN_LANDFILL",rs.getString("DIS_TN_LANDFILL"));
		jsonRecord.put("DIS_TP_SUM",rs.getString("DIS_TP_SUM"));
		jsonRecord.put("DIS_TP_POP",rs.getString("DIS_TP_POP"));
		jsonRecord.put("DIS_TP_ANI",rs.getString("DIS_TP_ANI"));
		jsonRecord.put("DIS_TP_IND",rs.getString("DIS_TP_IND"));
		jsonRecord.put("DIS_TP_LAND",rs.getString("DIS_TP_LAND"));
		jsonRecord.put("DIS_TP_FISH",rs.getString("DIS_TP_FISH"));
		jsonRecord.put("DIS_TP_LANDFILL",rs.getString("DIS_TP_LANDFILL"));
		jsonRecord.put("OUT_FLOW_SUM",rs.getString("OUT_FLOW_SUM"));
		jsonRecord.put("OUT_FLOW_POP",rs.getString("OUT_FLOW_POP"));
		jsonRecord.put("OUT_FLOW_ANI",rs.getString("OUT_FLOW_ANI"));
		jsonRecord.put("OUT_FLOW_IND",rs.getString("OUT_FLOW_IND"));
		jsonRecord.put("OUT_FLOW_LAND",rs.getString("OUT_FLOW_LAND"));
		jsonRecord.put("OUT_FLOW_FISH",rs.getString("OUT_FLOW_FISH"));
		jsonRecord.put("OUT_FLOW_LANDFILL",rs.getString("OUT_FLOW_LANDFILL"));
		jsonRecord.put("OUT_BOD_SUM",rs.getString("OUT_BOD_SUM"));
		jsonRecord.put("OUT_BOD_POP",rs.getString("OUT_BOD_POP"));
		jsonRecord.put("OUT_BOD_ANI",rs.getString("OUT_BOD_ANI"));
		jsonRecord.put("OUT_BOD_IND",rs.getString("OUT_BOD_IND"));
		jsonRecord.put("OUT_BOD_LAND",rs.getString("OUT_BOD_LAND"));
		jsonRecord.put("OUT_BOD_FISH",rs.getString("OUT_BOD_FISH"));
		jsonRecord.put("OUT_BOD_LANDFILL",rs.getString("OUT_BOD_LANDFILL"));
		jsonRecord.put("OUT_TN_SUM",rs.getString("OUT_TN_SUM"));
		jsonRecord.put("OUT_TN_POP",rs.getString("OUT_TN_POP"));
		jsonRecord.put("OUT_TN_ANI",rs.getString("OUT_TN_ANI"));
		jsonRecord.put("OUT_TN_IND",rs.getString("OUT_TN_IND"));
		jsonRecord.put("OUT_TN_LAND",rs.getString("OUT_TN_LAND"));
		jsonRecord.put("OUT_TN_FISH",rs.getString("OUT_TN_FISH"));
		jsonRecord.put("OUT_TN_LANDFILL",rs.getString("OUT_TN_LANDFILL"));
		jsonRecord.put("OUT_TP_SUM",rs.getString("OUT_TP_SUM"));
		jsonRecord.put("OUT_TP_POP",rs.getString("OUT_TP_POP"));
		jsonRecord.put("OUT_TP_ANI",rs.getString("OUT_TP_ANI"));
		jsonRecord.put("OUT_TP_IND",rs.getString("OUT_TP_IND"));
		jsonRecord.put("OUT_TP_LAND",rs.getString("OUT_TP_LAND"));
		jsonRecord.put("OUT_TP_FISH",rs.getString("OUT_TP_FISH"));
		jsonRecord.put("OUT_TP_LANDFILL",rs.getString("OUT_TP_LANDFILL"));
		jsonRecord.put("WS_NM",rs.getString("WS_NM"));
		jsonRecord.put("BASIN",rs.getString("BASIN"));
  		
  		
  		jsonArr.add(jsonRecord);
  		
	}
	
	jsonObj.put("data", jsonArr);
   //console.info(jsonObj);
   out.print(jsonObj);
   //out.print("success");
}catch(Exception ex){
	//throw;
	System.out.println(ex);
	System.out.println(sql);
	out.print("error");
} 
%>
<%@ include file="dbClose.jsp" %>